[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read", path = "./broadcast" },
  { access = "read", path = "./reports" },
  { access = "write", path = "./reports" }
]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@forge-std/=lib/forge-std/src/",
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "@octant-v2-core/=lib/octant-v2-core/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

solc = "0.8.30"
optimizer = true
optimizer_runs = 1000

[fmt]
tab_width = 4
line_length = 120
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true
number_underscore = "thousands"

[rpc_endpoints]
tenderlyVNet = "https://virtual.mainnet.eu.rpc.tenderly.co/82c86106-662e-4d7f-a974-c311987358ff"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
