[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc = "0.8.30"
optimizer = true
optimizer_runs = 1000

[fmt]
tab_width = 4
line_length = 120
bracket_spacing = true
int_types = "long"
quote_style = "double"
wrap_comments = true
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
